/**
 * Wager V3 — KISS VM Prediction Market Contract (MAST)
 *
 * State layout:
 *   Port 0  = ownerpk        (owner's signing public key)
 *   Port 1  = owneraddr      (owner's payout address)
 *   Port 2  = arbpk          (arbiter's signing public key)
 *   Port 3  = arbaddr        (arbiter's payout address — receives 10% of total pot on dispute)
 *   Port 4  = phase          (0=open order, 1=matched bet)
 *   Port 5  = timeout        (blocks before arbiter timeout in phase 1)
 *   Port 6  = side           (1=FOR, 0=AGAINST — owner's side)
 *   Port 7  = wantstake      (amount counter must put up)
 *   Port 8  = counterpk      (counter's signing public key — set at fill)
 *   Port 9  = counteraddr    (counter's payout address — set at fill)
 *   Port 10 = ownerstake     (enforced = @AMOUNT at fill time)
 *   Port 11 = outcome        (1=FOR/won, 0=AGAINST/lost — set by both self-settle AND arbiter)
 *   Port 12 = proposition    (hex-encoded event description text)
 *   Port 13 = settlement     (target block number, 0=anytime)
 *   Port 14 = refresh flag   (1=refresh tx, used by MAST refresh path)
 *
 * Main script paths:
 *   Phase 0, SIGNEDBY(owner)              → Cancel OR Refresh open bet
 *   Phase 0, anyone                       → Fill (combine stakes, phase→1)
 *   Phase 1, SIGNEDBY(both bettors)       → Self-settle (0% fee, escrow returned to loser)
 *   Phase 1, SIGNEDBY(arbiter) o=0|1      → Arbiter resolve (10% of total pot, loser forfeits all)
 *
 * MAST paths (Refresh + Timeout):
 *   Phase 1, STATE(14)=1, SIGNEDBY(owner|counter) → Refresh matched bet
 *   Phase 1, @COINAGE GT timeout                  → Timeout (refund both proportionally)
 *
 * Escrow math (self-settle):
 *   Each side locks bet * 1.25 (25% escrow). Escrow = lock / 5.
 *   Winner gets: @AMOUNT - loserEscrow. Loser gets: loserEscrow back.
 */

var WAGER_SCRIPT =
    "LET ok=PREVSTATE(0) LET oa=PREVSTATE(1) LET ak=PREVSTATE(2) LET aa=PREVSTATE(3) " +
    "LET ph=PREVSTATE(4) LET sd=PREVSTATE(6) LET ws=PREVSTATE(7) " +
    "IF ph EQ 0 THEN " +
        "IF SIGNEDBY(ok) THEN RETURN TRUE ENDIF " +
        "ASSERT SAMESTATE(0 3) ASSERT STATE(4) EQ 1 ASSERT SAMESTATE(5 7) " +
        "ASSERT STATE(10) EQ @AMOUNT " +
        "ASSERT ak NEQ ok ASSERT ak NEQ STATE(8) " +
        "ASSERT VERIFYOUT(@INPUT @ADDRESS @AMOUNT+ws @TOKENID TRUE) " +
        "RETURN TRUE " +
    "ENDIF " +
    "LET ck=PREVSTATE(8) LET ca=PREVSTATE(9) LET os=PREVSTATE(10) " +
    "IF ph EQ 1 AND SIGNEDBY(ok) AND SIGNEDBY(ck) AND STATE(11) NEQ 2 THEN " +
        "LET o=STATE(11) " +
        "IF o EQ sd THEN " +
            "LET le=(@AMOUNT-os)/5 " +
            "ASSERT VERIFYOUT(@INPUT oa @AMOUNT-le @TOKENID FALSE) " +
            "ASSERT VERIFYOUT(@INPUT+1 ca le @TOKENID FALSE) " +
        "ELSE " +
            "LET le=os/5 " +
            "ASSERT VERIFYOUT(@INPUT ca @AMOUNT-le @TOKENID FALSE) " +
            "ASSERT VERIFYOUT(@INPUT+1 oa le @TOKENID FALSE) " +
        "ENDIF " +
        "RETURN TRUE " +
    "ENDIF " +
    "IF ph EQ 1 AND SIGNEDBY(ak) THEN " +
        "LET f=@AMOUNT/10 LET o=STATE(11) " +
        "IF o EQ sd THEN " +
            "ASSERT VERIFYOUT(@INPUT oa @AMOUNT-f @TOKENID FALSE) " +
        "ELSE " +
            "ASSERT VERIFYOUT(@INPUT ca @AMOUNT-f @TOKENID FALSE) " +
        "ENDIF " +
        "ASSERT VERIFYOUT(@INPUT+1 aa f @TOKENID FALSE) " +
        "RETURN TRUE " +
    "ENDIF " +
    "MAST 0x9C840B211A221ADEFAC2C9893899E0A1361594DF168BCDD04C3A865BB4DD1F6C " +
    "RETURN FALSE";

// MAST leaf scripts + proofs (generated by mmrcreate — 3 leaves: refresh, timeout, void)
var MAST_REFRESH_SCRIPT = "LET ok=PREVSTATE(0) LET ck=PREVSTATE(8) LET ph=PREVSTATE(4) IF ph EQ 1 AND STATE(14) EQ 1 AND (SIGNEDBY(ok) OR SIGNEDBY(ck)) THEN ASSERT SAMESTATE(0 12) ASSERT VERIFYOUT(@INPUT @ADDRESS @AMOUNT @TOKENID TRUE) RETURN TRUE ENDIF RETURN FALSE";
var MAST_REFRESH_PROOF = "0x0001000001020000000020565DF2572EE233DB75B44201D90052EC2ABC36B852FEB7EC0B1E4273ACF07C3D0001000000000020C48ECF868DC008BBEE74735AC445A6971ADA970FB27A8B35C8BDE735E560B55C000100";

var MAST_TIMEOUT_SCRIPT = "LET oa=PREVSTATE(1) LET ca=PREVSTATE(9) LET os=PREVSTATE(10) LET ph=PREVSTATE(4) LET to=PREVSTATE(5) IF ph EQ 1 AND @COINAGE GT to THEN ASSERT VERIFYOUT(@INPUT oa os @TOKENID FALSE) ASSERT VERIFYOUT(@INPUT+1 ca @AMOUNT-os @TOKENID FALSE) RETURN TRUE ENDIF RETURN FALSE";
var MAST_TIMEOUT_PROOF = "0x00010000010201000000204707FF4F1658D2DB8E19A454D943A4A4A283E513D03DE1CACCA1005B0EDBAA250001000000000020C48ECF868DC008BBEE74735AC445A6971ADA970FB27A8B35C8BDE735E560B55C000100";

var MAST_VOID_SCRIPT = "LET ok=PREVSTATE(0) LET oa=PREVSTATE(1) LET ck=PREVSTATE(8) LET ca=PREVSTATE(9) LET os=PREVSTATE(10) LET ph=PREVSTATE(4) IF ph EQ 1 AND SIGNEDBY(ok) AND SIGNEDBY(ck) AND STATE(11) EQ 2 THEN ASSERT VERIFYOUT(@INPUT oa os @TOKENID FALSE) ASSERT VERIFYOUT(@INPUT+1 ca @AMOUNT-os @TOKENID FALSE) RETURN TRUE ENDIF RETURN FALSE";
var MAST_VOID_PROOF = "0x0001000001010100000020CB91ACFC586EB3E102F96F193B39B243570CE1194903B2F39C19AB9D983D2AC9000100";

var WAGER_SCRIPT_ADDRESS = "";

function registerContract(callback) {
    MDS.cmd('newscript trackall:true script:"' + WAGER_SCRIPT + '"', function(res) {
        if (res.status) {
            WAGER_SCRIPT_ADDRESS = res.response.address;
            MDS.log("Wager V3 contract at: " + WAGER_SCRIPT_ADDRESS);
        }
        if (callback) callback(res);
    });
}